Advantages and benefits of the “MySQL Connector Python” module: –

    MySQL Connector Python module is written in pure Python, and it is self-sufficient to execute database queries through Python.
    It is an official Oracle-supported driver to work with MySQL and Python.
    It is Python 3 compatible and actively maintained.

Note: This lab focuses on the “MySQL Connector Python” module. All examples are created using MySQL Connector Python.

Sample Database:
We will use the “classicmodels” database for this lab. If you do not have “classicmodels” database. Click here to download the database script file and the classicmodels.sql file will be downloaded to your computer. After downloading, you have to run “classicmodels.sql” file in MariaDB.   
 
How to Connect to SQL(Maria) Database in Python

Install MySQL connector module

Use the pip command to install SQL connector Python.
pip install mysql-connector-python

Import SQL connector module

Import using an import mysql.connector statement so you can use this module’s methods to communicate with the SQL database.

Use the connect() method

Use the connect() method of the SQL Connector class with the required arguments to connect SQL. It would return a connector object if the connection established successfully

Use the cursor() method

Use the cursor() method of a Connection object to create a cursor object to perform various SQL operations.

Use the execute() method

The execute() methods run the SQL query and return the result.

Extract result using fetchall()
Use cursor.fetchall() or fetchone() or fetchmany() to read query result.

Close cursor and connection objects
use cursor.clsoe() and connection.clsoe() method to close open connections after your work completes

Example  One: Connect to MariabDB in Python (You can use jupyter notebook)

In [9]:
import mysql.connector as mariadb
from mysql.connector import Error
import numpy as np
import pandas as pd

try:
    connection = mariadb.connect(host='localhost',
                                         database='classicmodels',
                                         user='root',
                                         password='password',
                                         charset= 'latin1')
    if connection.is_connected():
        db_Info = connection.get_server_info()
        print("Connected to SQL  version ", db_Info)
        cursor = connection.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)
        cursor = connection.cursor()
        sql_select_Query = "select * from offices"
        cursor = connection.cursor()
        cursor.execute(sql_select_Query)
       # get all records
        records = cursor.fetchall()
        print("Total number of rows in table: ", cursor.rowcount)

        print("\nPrinting each row")
        for row in records:
	        print("Id = ", row[0], )
	        print("Name = ", row[1])
	        print("Price  = ", row[2])
	        print("Purchase date  = ", row[3], "\n")
      
except Error as e:
    print("Error while connecting to Database", e)
finally:
    if connection.is_connected():
        cursor.close()
        connection.close()
        print("Database connection is closed")

Connected to SQL  version  5.5.5-10.9.4-MariaDB
You're connected to database:  ('classicmodels',)
Total number of rows in table:  7

Printing each row
Id =  1
Name =  San Francisco
Price  =  +1 650 219 4782
Purchase date  =  100 Market Street

Id =  2
Name =  Boston
Price  =  +1 215 837 0825
Purchase date  =  1550 Court Place

Id =  3
Name =  NYC
Price  =  +1 212 555 3000
Purchase date  =  523 East 53rd Street

Id =  4
Name =  Paris
Price  =  +33 14 723 4404
Purchase date  =  43 Rue Jouffroy D'abbans

Id =  5
Name =  Tokyo
Price  =  +81 33 224 5000
Purchase date  =  4-1 Kioicho

Id =  6
Name =  Sydney
Price  =  +61 2 9264 2451
Purchase date  =  5-11 Wentworth Avenue

Id =  7
Name =  London
Price  =  +44 20 7877 2041
Purchase date  =  25 Old Broad Street

Database connection is closed

Points to remember

Catch exceptions that may occur during this process by importing the Error class from the MySQL connector python module using a from mysql.connector import Error statement.
Error class is useful to debug when we fail to connect to MariaDB. For example, ACCESS DENIED ERROR when the username or password is wrong.

The connect() method can throw a Database error exception if one of the required parameters is wrong. For example, if you provide a database name that is not present in MariaDB.

The is_connected() is the method of the MySQLConnection class through which we can verify if our Python application is connected to MariaDB.

At last, we are closing the MySQL database connection using a close() method of MySQLConnection class.

Example Two : The following example uses the HAVING clause to find orders that have total amounts greater than 1000 and contain more than 600 items:

In [12]:
import mysql.connector
from mysql.connector import Error

try:
        connection = mysql.connector.connect(host='localhost',
                                             database='classicmodels',
                                             user='root',
                                             password='password',
                                             charset = 'latin1')
        if connection.is_connected():
            db_Info = connection.get_server_info()
            cursor = connection.cursor()
            SQLQuery ="SELECT ordernumber, SUM(quantityOrdered) AS itemsCount, SUM(priceeach*quantityOrdered) AS total FROM orderdetails GROUP BY ordernumber HAVING    total > 1000    AND    itemsCount > 600";
            cursor.execute(SQLQuery)
            
            # get all records
            records = cursor.fetchall() 
            print("Total number of rows in table: ", cursor.rowcount)    
            print("\nPrinting each row")
            for row in records:
                print("order number = ", row[0],  )
                print("item counts = ", row[1])
                print("total  = ", row[2], "\n" )
except Error as e:
        print("Error while connecting to Database", e)
finally:
        if connection.is_connected():
         cursor.close()
        connection.close()
        print("Database connection is closed")

Total number of rows in table:  22

Printing each row
order number =  10106
item counts =  675
total  =  52151.81

order number =  10126
item counts =  617
total  =  57131.92

order number =  10135
item counts =  607
total  =  55601.84

order number =  10165
item counts =  670
total  =  67392.85

order number =  10168
item counts =  642
total  =  50743.65

order number =  10204
item counts =  619
total  =  58793.53

order number =  10207
item counts =  615
total  =  59265.14

order number =  10212
item counts =  612
total  =  59830.55

order number =  10222
item counts =  717
total  =  56822.65

order number =  10262
item counts =  605
total  =  47065.36

order number =  10275
item counts =  601
total  =  47924.19

order number =  10310
item counts =  619
total  =  61234.67

order number =  10312
item counts =  601
total  =  55639.66

order number =  10316
item counts =  623
total  =  46788.14

order number =  10332
item counts =  621
total  =  47159.11

order number =  10339
item counts =  614
total  =  48927.64

order number =  10360
item counts =  620
total  =  52166.00

order number =  10373
item counts =  605
total  =  46770.52

order number =  10386
item counts =  650
total  =  46968.52

order number =  10390
item counts =  603
total  =  55902.50

order number =  10398
item counts =  629
total  =  46656.94

order number =  10414
item counts =  609
total  =  50806.85

Database connection is closed